# https://fabricmc.net/develop/

[versions]
# https://maven.shedaniel.me/me/shedaniel/cloth/
cloth = "20.0.149"
fabricLoader = "0.18.1"
minecraft = "1.21.11"
# https://projects.neoforged.net/neoforged/neoforge
neoforge= "21.11.0-beta"
# https://projects.neoforged.net/neoforged/neoform
neoform = "1.21.11-20251209.172050"

[plugins]

[libraries]
mixin = "org.spongepowered:mixin:0.8.7"
mixinExtras = "io.github.llamalad7:mixinextras-common:0.5.0"

fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricLoader-junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabricLoader" }
fabricMinecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

concurrentutil = "ca.spottedleaf:concurrentutil:0.0.7"

yamlconfig = "ca.spottedleaf:yamlconfig:1.1.0"
snakeyaml = "org.yaml:snakeyaml:2.5"

clothConfig-neoforge = { module = "me.shedaniel.cloth:cloth-config-neoforge", version.ref = "cloth" }
clothConfig-fabric = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth" }
modmenu = "com.terraformersmc:modmenu:17.0.0-alpha.1"

asm = "org.ow2.asm:asm:9.8"
